package grpc

import (
	"context"
	"fmt"
	"io"
	"log"
	"strconv"

	dresl "github.com/aditya3232/my-grpc-go-server/internal/application/domain/resiliency"
	resl "github.com/aditya3232/my-grpc-proto/protogen/go/resiliency"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// fungsi helper yang mengubah kode status (angka) menjadi gRPC error
func generateErrStatus(statusCode uint32) error {
	str := "Generated by server"

	if sc, ok := dresl.StatusCodeMap[statusCode]; ok && sc == codes.OK {
		return nil
	}

	if sc, ok := dresl.StatusCodeMap[statusCode]; ok {
		return status.New(sc, str).Err()
	} else {
		return status.New(codes.Internal, str).Err()
	}

}

// UnaryResiliency adalah gRPC unary handler untuk menguji resiliency (ketahanan) client
// terhadap kondisi delay dan error yang tidak menentu dari server.
//
// Alur kerja:
//  1. Menerima request berisi rentang delay (MinDelaySecond, MaxDelaySecond) dan daftar
//     kandidat status code (StatusCodes) yang dikirim oleh client.
//  2. Memanggil resiliencyService.GenerateResiliency untuk mensimulasikan latency acak
//     dalam rentang delay tersebut, lalu memilih salah satu status code dari daftar yang diberikan.
//  3. Jika status code hasil generate bukan OK, handler akan mengembalikan gRPC error
//     yang sesuai (lihat generateErrStatus) tanpa mengirim response sukses.
//  4. Jika status code adalah OK, handler mengembalikan response berisi DummyString
//     sebagai tanda request berhasil diproses.
//
// Fungsi ini biasanya digunakan untuk keperluan chaos testing / simulasi kegagalan server,
// sehingga tim dapat menguji mekanisme resiliency di sisi client seperti retry,
// circuit breaker, atau timeout handling.
func (a *GrpcAdapter) UnaryResiliency(ctx context.Context, req *resl.ResiliencyRequest) (*resl.ResiliencyResponse, error) {
	log.Println("UnaryResiliency called")

	str, sts := a.resiliencyService.GenerateResiliency(req.MinDelaySecond, req.MaxDelaySecond, req.StatusCodes)

	if errStatus := generateErrStatus(sts); errStatus != nil {
		return nil, errStatus
	}

	return &resl.ResiliencyResponse{
		DummyString: str,
	}, nil
}

// ServerStreamingResiliency adalah gRPC server-streaming handler untuk menguji resiliency
// client terhadap aliran data (stream) yang memiliki delay dan potensi error yang tidak menentu.
//
// Alur kerja:
//  1. Mengambil context dari stream untuk memantau apakah client membatalkan koneksi
//     (misalnya karena timeout atau client menutup request).
//  2. Masuk ke loop tanpa henti (infinite loop) yang terus mengirim response ke client
//     selama koneksi masih aktif.
//  3. Pada setiap iterasi:
//     - Jika context sudah Done (client cancel/disconnect), log pesan dan hentikan stream
//     dengan return nil (bukan error, karena ini kondisi normal).
//     - Jika belum, panggil GenerateResiliency untuk mensimulasikan delay acak dan
//     memilih status code dari daftar yang dikirim client.
//  4. Jika status code hasil generate bukan OK, hentikan stream dan kirim gRPC error
//     ke client (lihat generateErrStatus).
//  5. Jika OK, kirim response berisi DummyString ke client melalui stream.Send,
//     lalu lanjut ke iterasi berikutnya (mengirim response lagi, terus-menerus).
//
// Catatan: fungsi ini akan terus mengirim data tanpa henti selama tidak ada error
// dan client belum membatalkan koneksi — cocok untuk mensimulasikan long-lived stream
// yang rentan terhadap delay/error, guna menguji mekanisme resiliency di sisi client
// seperti reconnect, backoff, atau stream timeout handling.
func (a *GrpcAdapter) ServerStreamingResiliency(req *resl.ResiliencyRequest, stream grpc.ServerStreamingServer[resl.ResiliencyResponse]) error {
	log.Println("ServerStreamingResiliency called")

	context := stream.Context()

	for {
		select {
		case <-context.Done():
			log.Println("Client cancelled request")
			return nil
		default:
			str, sts := a.resiliencyService.GenerateResiliency(req.MinDelaySecond, req.MaxDelaySecond, req.StatusCodes)
			if errStatus := generateErrStatus(sts); errStatus != nil {
				return errStatus
			}

			stream.Send(&resl.ResiliencyResponse{
				DummyString: str,
			})
		}
	}
}

// ClientStreamingResiliency adalah gRPC client-streaming handler untuk menguji resiliency
// server dalam menerima banyak request secara berturut-turut dari client dalam satu stream.
//
// Alur kerja:
//  1. Masuk ke loop tanpa henti untuk terus menerima request dari client melalui stream.Recv().
//  2. Jika error yang diterima adalah io.EOF, artinya client sudah selesai mengirim semua
//     request dan menutup sisi kirimnya. Server kemudian membalas sekali saja (SendAndClose)
//     dengan response berisi jumlah total request yang berhasil diterima (variabel i),
//     lalu menutup stream.
//  3. Jika request berhasil diterima (req != nil), panggil GenerateResiliency untuk
//     mensimulasikan delay acak dan memilih status code dari daftar yang dikirim client
//     pada request tersebut.
//  4. Jika status code hasil generate bukan OK, handler langsung menghentikan stream
//     dan mengembalikan gRPC error ke client (lihat generateErrStatus), tanpa mengirim
//     response ringkasan.
//  5. Jika OK, counter i ditambah 1 dan loop lanjut ke iterasi berikutnya untuk
//     menerima request selanjutnya.
//
// Fungsi ini cocok untuk mensimulasikan skenario upload/batch dari client, guna menguji
// bagaimana client menangani kegagalan di tengah proses pengiriman banyak request
// (misalnya retry per-chunk atau abort keseluruhan proses).
func (a *GrpcAdapter) ClientStreamingResiliency(stream grpc.ClientStreamingServer[resl.ResiliencyRequest, resl.ResiliencyResponse]) error {
	log.Println("ClientStreamingResiliency called")

	i := 0

	for {
		req, err := stream.Recv()

		if err == io.EOF {
			res := resl.ResiliencyResponse{
				DummyString: fmt.Sprintf("Received %v requests from client", strconv.Itoa(i)),
			}

			return stream.SendAndClose(&res)
		}

		if req != nil {
			_, sts := a.resiliencyService.GenerateResiliency(req.MinDelaySecond,
				req.MaxDelaySecond, req.StatusCodes)

			if errStatus := generateErrStatus(sts); errStatus != nil {
				return errStatus
			}
		}

		i = i + 1
	}
}

// BiDirectionalResiliency adalah gRPC bidirectional-streaming handler untuk menguji
// resiliency dalam skenario komunikasi dua arah (client dan server bisa saling kirim
// data secara bersamaan dalam satu stream).
//
// Alur kerja:
//  1. Mengambil context dari stream untuk memantau apakah client membatalkan koneksi.
//  2. Masuk ke loop tanpa henti selama koneksi masih aktif:
//     - Jika context sudah Done (client cancel/disconnect), log pesan dan hentikan
//     stream dengan return nil.
//     - Jika belum, coba terima request berikutnya dari client via stream.Recv().
//  3. Jika error yang diterima adalah io.EOF, artinya client sudah selesai mengirim
//     semua request, maka handler mengembalikan nil untuk menutup stream secara normal.
//  4. Jika ada error lain saat menerima request, saat ini di-log dengan log.Fatalln
//     (lihat catatan di bawah).
//  5. Jika request berhasil diterima, panggil GenerateResiliency untuk mensimulasikan
//     delay acak dan memilih status code dari daftar yang dikirim client.
//  6. Jika status code hasil generate bukan OK, hentikan stream dan kirim gRPC error
//     ke client (lihat generateErrStatus).
//  7. Jika OK, kirim response berisi DummyString kembali ke client via stream.Send.
//     Jika pengiriman gagal, saat ini juga di-log dengan log.Fatalln.
//
// Fungsi ini mensimulasikan komunikasi dua arah yang rentan delay/error di kedua sisi,
// guna menguji resiliency client maupun server dalam skenario streaming interaktif
// (misalnya chat, live update, atau sinkronisasi data real-time).
func (a *GrpcAdapter) BiDirectionalResiliency(stream grpc.BidiStreamingServer[resl.ResiliencyRequest, resl.ResiliencyResponse]) error {
	log.Println("BiDirectionalResiliency called")

	context := stream.Context()

	for {
		select {
		case <-context.Done():
			log.Println("Client cancelled request")
			return nil
		default:
			req, err := stream.Recv()

			if err == io.EOF {
				return nil
			}

			if err != nil {
				log.Fatalln("Error while reading from client :", err)
			}

			str, sts := a.resiliencyService.GenerateResiliency(req.MinDelaySecond,
				req.MaxDelaySecond, req.StatusCodes)

			if errStatus := generateErrStatus(sts); errStatus != nil {
				return errStatus
			}

			err = stream.Send(
				&resl.ResiliencyResponse{
					DummyString: str,
				},
			)

			if err != nil {
				log.Fatalln("Error while sending response to client :", err)
			}
		}
	}
}
